baseURL = 'http://example.org/'
languageCode = 'pt-br'
title = 'Meu Blog Técnico'
theme = 'ananke' # <-- Adicione/edite esta linha para 'ananke'
defaultContentLanguage = 'pt-br' # <--- Sugestão: Adicione para conteúdo em português
